"""
Auto-Submit Bounties — uses LLM to generate solutions for high-value
GitHub Issues, posts comments, and creates pull requests via the GitHub API.

Workflow:
  1. Pick top-scoring bounty from DB
  2. LLM generates solution text based on issue description
  3. Reference solution posted as comment (not PR — safer, builds reputation)
  4. Bounty status updated to APPLIED in DB

Requirements:
  - GITHUB_TOKEN with 'public_repo' scope (for commenting on public repos)
  - Ollama running locally for LLM solution generation
"""

import logging
from datetime import datetime, timezone
from typing import Optional

import httpx
from sqlalchemy.orm import Session

from app.config import settings
from app.db.models import Bounty, BountyStatus
from app.utils.notify import notify_alert, notify_error
from app.utils.budget import can_spend, record_spend

logger = logging.getLogger("buckgen.submit")

GITHUB_API = "https://api.github.com"


async def generate_solution(
    title: str,
    description: str,
    reward: float,
    currency: str,
) -> str:
    """
    Use the local Ollama LLM to generate a solution for a bounty issue.

    Args:
        title: Issue title
        description: Issue body
        reward: Reward amount
        currency: Reward currency

    Returns:
        Generated solution text (or fallback if LLM unavailable).
    """
    # Tiered LLM parameters based on bounty value
    # Higher-value bounties get more attention (more tokens, more creative)
    if reward >= 1000:
        temperature, max_tokens, max_words = 0.8, 4000, 1000
        quality_tier = "premium"
    elif reward >= 100:
        temperature, max_tokens, max_words = 0.7, 2000, 600
        quality_tier = "standard"
    else:
        temperature, max_tokens, max_words = 0.5, 1200, 400
        quality_tier = "basic"

    prompt = (
        f"You are a skilled developer responding to a paid bounty issue ({quality_tier} quality).\n\n"
        f"BOUNTY: {title}\n"
        f"REWARD: ${reward} {currency}\n"
        f"DESCRIPTION:\n{description[:2000]}\n\n"
        f"Write a complete, technically accurate response that:\n"
        f"1. Shows deep understanding of the issue and requirements\n"
        f"2. Outlines a concrete implementation plan\n"
        f"3. Includes production-ready code snippets or complete implementations\n"
        f"4. References relevant libraries, APIs, or design patterns\n"
        f"5. Is professional and demonstrates senior-level competence\n\n"
        f"Keep it under {max_words} words. Include code in markdown blocks."
    )

    try:
        async with httpx.AsyncClient(timeout=90.0) as client:
            resp = await client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.OLLAMA_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": temperature, "num_predict": max_tokens},
                },
            )
            if resp.status_code == 200:
                return resp.json().get("response", "")
            else:
                logger.warning(
                    "LLM returned HTTP %d: %s", resp.status_code, resp.text[:100]
                )
    except httpx.RequestError as exc:
        logger.warning("LLM unavailable: %s", exc)

    # Fallback: template-based response
    return (
        f"Hi! I'd like to work on this bounty issue.\n\n"
        f"I've reviewed the requirements for '{title}' "
        f"and believe I can deliver a quality solution.\n\n"
        f"**Approach:**\n"
        f"- Analyze the existing codebase and requirements\n"
        f"- Implement the requested changes following project conventions\n"
        f"- Add tests and documentation as needed\n"
        f"- Submit for review within the expected timeline\n\n"
        f"Please let me know if you'd like me to proceed with implementation!\n\n"
        f"*Generated by BuckGen automated bounty agent*"
    )


async def _github_request(
    method: str,
    url: str,
    json_data: dict | None = None,
    retries: int = 2,
) -> httpx.Response | None:
    """
    Make an authenticated GitHub API request with retries.

    Args:
        method: HTTP method (GET, POST, etc.)
        url: Full API URL
        json_data: Optional JSON body
        retries: Number of retries on transient errors

    Returns:
        Response object or None on failure.
    """
    headers = {
        "Accept": "application/vnd.github.v3+json",
    }
    if settings.GITHUB_TOKEN:
        headers["Authorization"] = f"Bearer {settings.GITHUB_TOKEN}"
    else:
        logger.warning("No GITHUB_TOKEN — cannot call GitHub API")
        return None

    for attempt in range(1 + retries):
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                resp = await client.request(
                    method, url, json=json_data, headers=headers
                )
                # Success
                if resp.status_code < 500:
                    return resp
                # Server error -> retry
                logger.warning(
                    "GitHub API HTTP %d (attempt %d/%d)",
                    resp.status_code,
                    attempt + 1,
                    retries + 1,
                )
        except (httpx.RequestError, httpx.TimeoutException) as exc:
            logger.warning(
                "GitHub API error (attempt %d/%d): %s", attempt + 1, retries + 1, exc
            )

        if attempt < retries:
            import asyncio

            await asyncio.sleep(2 * (attempt + 1))  # exponential backoff

    return None


async def create_fork(repo: str) -> str | None:
    """
    Fork a repository under the authenticated user.

    Args:
        repo: "owner/repo" format

    Returns:
        Full name of the fork ("user/repo") or None.
    """
    url = f"{GITHUB_API}/repos/{repo}/forks"
    resp = await _github_request("POST", url)

    if resp and resp.status_code in (202, 200):
        fork_data = resp.json()
        fork_full = fork_data.get("full_name", "")
        logger.info("Created fork: %s (from %s)", fork_full, repo)
        return fork_full

    logger.warning(
        "Fork failed for %s (HTTP %s)",
        repo,
        resp.status_code if resp else "no response",
    )
    return None


async def create_pull_request(
    repo: str,
    issue_number: int,
    branch_name: str,
    solution_body: str,
) -> bool:
    """
    Create a pull request linking to the bounty issue.

    Args:
        repo: "owner/repo" format
        issue_number: GitHub issue number
        branch_name: Name of the branch with changes
        solution_body: PR description body

    Returns:
        True if PR was created successfully.
    """
    # Only create PRs for high-value bounties (>= $100)
    pr_url = f"{GITHUB_API}/repos/{repo}/pulls"
    pr_data = {
        "title": f"Solution for #{issue_number}",
        "body": f"## Solution\n\n{solution_body[:2000]}\n\n---\n*Automated PR by BuckGen bounty agent*\n\nCloses #{issue_number}",
        "head": branch_name,
        "base": "main",
    }

    resp = await _github_request("POST", pr_url, pr_data)
    if resp and resp.status_code in (201, 200):
        logger.info("PR created for %s#%d", repo, issue_number)
        return True

    # Try "master" as base branch
    pr_data["base"] = "master"
    resp = await _github_request("POST", pr_url, pr_data)
    if resp and resp.status_code in (201, 200):
        logger.info("PR created for %s#%d (base: master)", repo, issue_number)
        return True

    logger.warning("PR creation failed for %s#%d", repo, issue_number)
    return False


async def post_comment(
    repo: str,
    issue_number: int,
    body: str,
) -> bool:
    """
    Post a comment on a GitHub issue with retry support.

    Args:
        repo: "owner/repo" format
        issue_number: Issue number
        body: Comment body text

    Returns:
        True if comment was posted successfully.
    """
    url = f"{GITHUB_API}/repos/{repo}/issues/{issue_number}/comments"
    resp = await _github_request("POST", url, {"body": body})

    if resp and resp.status_code in (201, 200):
        logger.info("Comment posted on %s#%d", repo, issue_number)
        return True

    logger.warning("GitHub comment failed for %s#%d", repo, issue_number)
    return False


async def submit_bounty(
    db: Session,
    bounty_id: int,
) -> dict:
    """
    Generate a solution and submit it for a specific bounty.

    Args:
        db: Database session
        bounty_id: Bounty ID in DB

    Returns:
        Submission result dict.
    """
    bounty = db.query(Bounty).filter(Bounty.id == bounty_id).first()
    if not bounty:
        return {"success": False, "error": "Bounty not found"}

    if bounty.status != BountyStatus.OPEN:
        return {
            "success": False,
            "error": f"Bounty status is {bounty.status.value}, not OPEN",
        }

    # Budget check (each submission costs ~$0.01 in LLM compute)
    if not can_spend(db, 0.01):
        return {"success": False, "error": "Budget cap reached"}

    logger.info("Submitting bounty #%d: %s", bounty.id, bounty.title[:60])

    # Parse repo and issue number from URL
    # URL format: https://github.com/owner/repo/issues/123
    url_parts = bounty.url.rstrip("/").split("/")
    if len(url_parts) < 7 or "issues" not in url_parts:
        return {
            "success": False,
            "error": f"Could not parse issue URL: {bounty.url}",
        }

    # Find the 'issues' segment and get the issue number
    try:
        issues_idx = url_parts.index("issues")
        repo = "/".join(url_parts[3:issues_idx])
        issue_number = int(url_parts[issues_idx + 1])
    except (ValueError, IndexError):
        return {
            "success": False,
            "error": f"Could not parse issue number from: {bounty.url}",
        }

    # Generate solution
    solution = await generate_solution(
        title=bounty.title,
        description=bounty.description,
        reward=bounty.reward_amount,
        currency=bounty.reward_currency,
    )

    # Post comment (with retry support)
    posted = await post_comment(repo, issue_number, solution)

    pr_created = False
    if posted:
        # For high-value bounties (>= $100), also try to create a PR
        if bounty.reward_amount >= 100:
            # Fork the repo
            fork_name = await create_fork(repo)
            if fork_name:
                # Create a branch name based on issue number
                branch_name = f"buckgen-solution-{issue_number}-{int(datetime.now(timezone.utc).timestamp())}"
                pr_created = await create_pull_request(
                    repo, issue_number, branch_name, solution
                )

        bounty.status = BountyStatus.APPLIED
        bounty.updated_at = datetime.now(timezone.utc)
        record_spend(db, 0.01, "llm", f"bounty submission #{bounty.id}")
        db.commit()

        notify_msg = (
            f"Bounty Submitted: {bounty.title[:40]}...\n"
            f"#{bounty.id} | {bounty.reward_amount} {bounty.reward_currency}\n"
            f"Repo: {repo}#{issue_number}"
        )
        if pr_created:
            notify_msg += "\n+ PR created!"

        await notify_alert(
            f"Bounty Submitted: {bounty.title[:40]}...",
            notify_msg,
        )

        return {
            "success": True,
            "bounty_id": bounty.id,
            "repo": repo,
            "issue_number": issue_number,
            "pr_created": pr_created,
            "solution_preview": solution[:200],
        }
    else:
        return {"success": False, "error": "Failed to post comment"}


async def submit_top_bounties(
    db: Session,
    max_submissions: int = 3,
    min_score: float = 0.7,
) -> list[dict]:
    """
    Find the highest-scoring OPEN bounties and submit solutions.

    Args:
        db: Database session
        max_submissions: Max bounties to submit in one run
        min_score: Minimum LLM score to consider

    Returns:
        List of submission results.
    """
    top_bounties = (
        db.query(Bounty)
        .filter(
            Bounty.status == BountyStatus.OPEN,
            Bounty.score >= min_score,
        )
        .order_by(Bounty.score.desc())
        .limit(max_submissions)
        .all()
    )

    if not top_bounties:
        logger.info("No qualifying bounties found for submission")
        return []

    logger.info(
        "Submitting solutions for %d top bounties (min score %.2f)",
        len(top_bounties),
        min_score,
    )

    results = []
    for bounty in top_bounties:
        result = await submit_bounty(db, bounty.id)
        results.append(result)

        # Brief delay between submissions
        if len(results) < max_submissions:
            import asyncio

            await asyncio.sleep(3)

    return results
